### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by nizar-tal** [willy-r/morse-translator#5]
Hello mate, here is a modest suggestion, instead of just using a command tu run the program like ```python morse.py -t 'morse code!'```, I think it is better to have a menu in order to improve the user experience and make more easy to use.

**Comment by nizar-tal** [comment]
I added a pull request in #6

**Comment by willy-r** [comment]
Hello @YoungMind44! Thanks for the suggestion and the precious time that you used to improve the user experiencie adding a menu, but I think that just the command line aproach is fine for now, if I need the menu I will search for your PR immediately! Again, thanks! ❤️

**Comment by nizar-tal** [comment]
No problem.
